# Generated by Django 4.1.2 on 2022-10-25 11:01

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(upload_to='posts/', verbose_name='Изображение')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('content', models.TextField(blank=True, default='Контент', null=True, verbose_name='Контент страницы')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_default', models.TextField()),
                ('body_editorjs', django_editorjs_fields.fields.EditorJsJSONField()),
                ('body_editorjs_text', django_editorjs_fields.fields.EditorJsTextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='users/', verbose_name='Изображение')),
                ('role', models.CharField(blank=True, max_length=50, null=True, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Номер выпуска')),
                ('title', models.CharField(max_length=50, verbose_name='Название выпуска')),
                ('description', models.TextField(verbose_name='Описание выпуска')),
                ('visibility', models.IntegerField(choices=[(1, 'Видим'), (0, 'Скрыт')], default=False, verbose_name='Видимость')),
                ('bg_left_color', colorfield.fields.ColorField(default='#ffc70080', image_field=None, max_length=18, samples=None, verbose_name='Задний фон (Начало)')),
                ('bg_right_color', colorfield.fields.ColorField(default='#ff7a0080', image_field=None, max_length=18, samples=None, verbose_name='Задний фон (Конец)')),
                ('title_left_color', colorfield.fields.ColorField(default='#ff4d4d', image_field=None, max_length=18, samples=None, verbose_name='Цвет заголовка (Начало)')),
                ('title_right_color', colorfield.fields.ColorField(default='#ff7a0080', image_field=None, max_length=18, samples=None, verbose_name='Цвет заголовка (Конец)')),
                ('editor_words', models.TextField(verbose_name='Слова редактора')),
                ('position', models.PositiveIntegerField(default=0)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editor', to='main.user', verbose_name='Главный редактор')),
                ('members', models.ManyToManyField(blank=True, to='main.user', verbose_name='Участники')),
                ('posts', models.ManyToManyField(blank=True, to='main.post', verbose_name='Посты')),
            ],
            options={
                'verbose_name': 'Выпуск',
                'verbose_name_plural': 'Выпуски',
                'ordering': ['position'],
            },
        ),
    ]
