# Generated by Django 4.1 on 2022-09-08 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Краткое описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notes_images/', verbose_name='Изображение')),
                ('note_type', models.CharField(choices=[('school_projects', 'Школьные проекты'), ('school_news', 'Школьные новости'), ('important', 'Разговор о важном'), ('journalism', 'Журналистика'), ('birthday', 'День рождения'), ('game', 'Игры'), ('other', 'Дургое')], default='other', max_length=15, verbose_name='Категория')),
                ('content', models.TextField(verbose_name='Контент страницы')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
