# Generated by Django 4.1 on 2022-10-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, default='Контент', null=True, verbose_name='Контент страницы'),
        ),
        migrations.AlterField(
            model_name='release',
            name='members',
            field=models.ManyToManyField(blank=True, to='main.user', verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='release',
            name='posts',
            field=models.ManyToManyField(blank=True, to='main.post', verbose_name='Посты'),
        ),
    ]
