# Generated by Django 4.1.2 on 2022-10-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
